// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.

#include "stereoSound.h"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_1;



standardInterfaces::stereoSound_ptr standardInterfaces::stereoSound_Helper::_nil() {
  return ::standardInterfaces::stereoSound::_nil();
}

::CORBA::Boolean standardInterfaces::stereoSound_Helper::is_nil(::standardInterfaces::stereoSound_ptr p) {
  return ::CORBA::is_nil(p);

}

void standardInterfaces::stereoSound_Helper::release(::standardInterfaces::stereoSound_ptr p) {
  ::CORBA::release(p);
}

void standardInterfaces::stereoSound_Helper::marshalObjRef(::standardInterfaces::stereoSound_ptr obj, cdrStream& s) {
  ::standardInterfaces::stereoSound::_marshalObjRef(obj, s);
}

standardInterfaces::stereoSound_ptr standardInterfaces::stereoSound_Helper::unmarshalObjRef(cdrStream& s) {
  return ::standardInterfaces::stereoSound::_unmarshalObjRef(s);
}

void standardInterfaces::stereoSound_Helper::duplicate(::standardInterfaces::stereoSound_ptr obj) {
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
}

standardInterfaces::stereoSound_ptr
standardInterfaces::stereoSound::_duplicate(::standardInterfaces::stereoSound_ptr obj)
{
  if( obj && !obj->_NP_is_nil() )  omni::duplicateObjRef(obj);
  return obj;
}

standardInterfaces::stereoSound_ptr
standardInterfaces::stereoSound::_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


standardInterfaces::stereoSound_ptr
standardInterfaces::stereoSound::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if( !obj || obj->_NP_is_nil() || obj->_NP_is_pseudo() ) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

standardInterfaces::stereoSound_ptr
standardInterfaces::stereoSound::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_stereoSound _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_stereoSound* _the_nil_ptr = 0;
  if( !_the_nil_ptr ) {
    omni::nilRefLock().lock();
    if( !_the_nil_ptr ) {
      _the_nil_ptr = new _objref_stereoSound;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* standardInterfaces::stereoSound::_PD_repoId = "IDL:standardInterfaces/stereoSound:1.0";


standardInterfaces::_objref_stereoSound::~_objref_stereoSound() {
  
}


standardInterfaces::_objref_stereoSound::_objref_stereoSound(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::standardInterfaces::stereoSound::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
standardInterfaces::_objref_stereoSound::_ptrToObjRef(const char* id)
{
  if( id == ::standardInterfaces::stereoSound::_PD_repoId )
    return (::standardInterfaces::stereoSound_ptr) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (::CORBA::Object_ptr) this;

  if( omni::strMatch(id, ::standardInterfaces::stereoSound::_PD_repoId) )
    return (::standardInterfaces::stereoSound_ptr) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (::CORBA::Object_ptr) this;

  return 0;
}

// Proxy call descriptor class. Mangled signature:
//  void_i_cPortTypes_mShortSequence_i_cPortTypes_mShortSequence
class _0RL_cd_409CFD756C2F18F0_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_409CFD756C2F18F0_00000000(LocalCallFn lcfn,const char* op_,size_t oplen,_CORBA_Boolean upcall=0):
     omniCallDescriptor(lcfn, op_, oplen, 0, 0, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

    
  
  PortTypes::ShortSequence_var arg_0_;
  const PortTypes::ShortSequence* arg_0;
  PortTypes::ShortSequence_var arg_1_;
  const PortTypes::ShortSequence* arg_1;
};

void _0RL_cd_409CFD756C2F18F0_00000000::marshalArguments(cdrStream& _n)
{
  (const PortTypes::ShortSequence&) *arg_0 >>= _n;
  (const PortTypes::ShortSequence&) *arg_1 >>= _n;

}

void _0RL_cd_409CFD756C2F18F0_00000000::unmarshalArguments(cdrStream& _n)
{
  arg_0_ = new PortTypes::ShortSequence;
  (PortTypes::ShortSequence&)arg_0_ <<= _n;
  arg_0 = &arg_0_.in();
  arg_1_ = new PortTypes::ShortSequence;
  (PortTypes::ShortSequence&)arg_1_ <<= _n;
  arg_1 = &arg_1_.in();

}

// Local call call-back function.
static void
_0RL_lcfn_409CFD756C2F18F0_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_409CFD756C2F18F0_00000000* tcd = (_0RL_cd_409CFD756C2F18F0_00000000*)cd;
  standardInterfaces::_impl_stereoSound* impl = (standardInterfaces::_impl_stereoSound*) svnt->_ptrToInterface(standardInterfaces::stereoSound::_PD_repoId);
  impl->pushPacket(*tcd->arg_0, *tcd->arg_1);


}

void standardInterfaces::_objref_stereoSound::pushPacket(const PortTypes::ShortSequence& left, const PortTypes::ShortSequence& right)
{
  _0RL_cd_409CFD756C2F18F0_00000000 _call_desc(_0RL_lcfn_409CFD756C2F18F0_10000000, "pushPacket", 11);
  _call_desc.arg_0 = &(PortTypes::ShortSequence&) left;
  _call_desc.arg_1 = &(PortTypes::ShortSequence&) right;

  _invoke(_call_desc);



}
standardInterfaces::_pof_stereoSound::~_pof_stereoSound() {}


omniObjRef*
standardInterfaces::_pof_stereoSound::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::standardInterfaces::_objref_stereoSound(ior, id);
}


::CORBA::Boolean
standardInterfaces::_pof_stereoSound::is_a(const char* id) const
{
  if( omni::ptrStrMatch(id, ::standardInterfaces::stereoSound::_PD_repoId) )
    return 1;
  
  return 0;
}

const standardInterfaces::_pof_stereoSound _the_pof_standardInterfaces_mstereoSound;

standardInterfaces::_impl_stereoSound::~_impl_stereoSound() {}


::CORBA::Boolean
standardInterfaces::_impl_stereoSound::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if( omni::strMatch(op, "pushPacket") ) {

    _0RL_cd_409CFD756C2F18F0_00000000 _call_desc(_0RL_lcfn_409CFD756C2F18F0_10000000, "pushPacket", 11, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
standardInterfaces::_impl_stereoSound::_ptrToInterface(const char* id)
{
  if( id == ::standardInterfaces::stereoSound::_PD_repoId )
    return (::standardInterfaces::_impl_stereoSound*) this;
  
  if( id == ::CORBA::Object::_PD_repoId )
    return (void*) 1;

  if( omni::strMatch(id, ::standardInterfaces::stereoSound::_PD_repoId) )
    return (::standardInterfaces::_impl_stereoSound*) this;
  
  if( omni::strMatch(id, ::CORBA::Object::_PD_repoId) )
    return (void*) 1;
  return 0;
}

const char*
standardInterfaces::_impl_stereoSound::_mostDerivedRepoId()
{
  return ::standardInterfaces::stereoSound::_PD_repoId;
}

POA_standardInterfaces::stereoSound::~stereoSound() {}

