<?xml version="1.0" encoding="us-ascii"?>
<!--
    Generated by Zeligsoft Component Enabler 2.0.2 (Build: 200510131317)
    http://www.zeligsoft.com
-->
<deploymentenforcement>
    <application id="DCE:438bffd7-cf7d-4f29-b0bc-e66303d25a84" name="Name" />
    <deviceassignmentsequence>
    </deviceassignmentsequence>
</deploymentenforcement>
