<?xml version="1.0" encoding="us-ascii"?>
<!DOCTYPE softwarecomponent SYSTEM "../dtd/softwarecomponent.dtd">
<!--
    Generated by Zeligsoft Component Enabler 2.0.2 (Build: 200510131317)
    http://www.zeligsoft.com
-->
<softwarecomponent>
    <corbaversion>2.2</corbaversion>
    <componentrepid repid="IDL:CF/Resource:1.0" />
    <componenttype>resource</componenttype>
    <componentfeatures>
        <supportsinterface repid="IDL:CF/Resource:1.0" supportsname="Resource" />
        <supportsinterface repid="IDL:CF/LifeCycle:1.0" supportsname="LifeCycle" />
        <supportsinterface repid="IDL:CF/PortSupplier:1.0" supportsname="PortSupplier" />
        <supportsinterface repid="IDL:CF/PropertySet:1.0" supportsname="PropertySet" />
        <supportsinterface repid="IDL:CF/TestableObject:1.0" supportsname="TestableObject" />
        <ports>
        </ports>
    </componentfeatures>
    <interfaces>
        <interface repid="IDL:CF/Resource:1.0" name="Resource">
            <!--[Inherited interface IDL:CF/LifeCycle:1.0]-->
            <inheritsinterface repid="IDL:CF/LifeCycle:1.0" />
            <!--[Inherited interface IDL:CF/PortSupplier:1.0]-->
            <inheritsinterface repid="IDL:CF/PortSupplier:1.0" />
            <!--[Inherited interface IDL:CF/PropertySet:1.0]-->
            <inheritsinterface repid="IDL:CF/PropertySet:1.0" />
            <!--[Inherited interface IDL:CF/TestableObject:1.0]-->
            <inheritsinterface repid="IDL:CF/TestableObject:1.0" />
        </interface>
    </interfaces>
</softwarecomponent>
