// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __complexChar_hh__
#define __complexChar_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_complexChar
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_complexChar
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_complexChar
#endif



#ifndef __PortTypes_hh_EXTERNAL_GUARD__
#define __PortTypes_hh_EXTERNAL_GUARD__
#include "ossie/PortTypes.h"
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE standardInterfaces

_CORBA_MODULE_BEG

#ifndef __standardInterfaces_mcomplexChar__
#define __standardInterfaces_mcomplexChar__
  class complexChar;
  class _objref_complexChar;
  class _impl_complexChar;
  
  typedef _objref_complexChar* complexChar_ptr;
  typedef complexChar_ptr complexCharRef;

  class complexChar_Helper {
  public:
    typedef complexChar_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_complexChar, complexChar_Helper> complexChar_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_complexChar,complexChar_Helper > complexChar_out;

#endif

  // interface complexChar
  class complexChar {
  public:
    // Declarations for this interface type.
    typedef complexChar_ptr _ptr_type;
    typedef complexChar_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_complexChar :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    void pushPacket(const ::PortTypes::CharSequence& I, const ::PortTypes::CharSequence& Q);

    // Constructors
    inline _objref_complexChar()  { _PR_setobj(0); }  // nil
    _objref_complexChar(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_complexChar();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_complexChar(const _objref_complexChar&);
    _objref_complexChar& operator = (const _objref_complexChar&);
    // not implemented

    friend class complexChar;
  };

  class _pof_complexChar : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_complexChar() : _OMNI_NS(proxyObjectFactory)(complexChar::_PD_repoId) {}
    virtual ~_pof_complexChar();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_complexChar :
    public virtual omniServant
  {
  public:
    virtual ~_impl_complexChar();

    virtual void pushPacket(const ::PortTypes::CharSequence& I, const ::PortTypes::CharSequence& Q) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_complexChar;

_CORBA_MODULE_END



_CORBA_MODULE POA_standardInterfaces
_CORBA_MODULE_BEG

  class complexChar :
    public virtual standardInterfaces::_impl_complexChar,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~complexChar();

    inline ::standardInterfaces::complexChar_ptr _this() {
      return (::standardInterfaces::complexChar_ptr) _do_this(::standardInterfaces::complexChar::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_standardInterfaces
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, standardInterfaces::complexChar_ptr _s);
void operator<<=(::CORBA::Any& _a, standardInterfaces::complexChar_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, standardInterfaces::complexChar_ptr& _s);



inline void
standardInterfaces::complexChar::_marshalObjRef(::standardInterfaces::complexChar_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_complexChar
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_complexChar
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_complexChar
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_complexChar
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_complexChar
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_complexChar
#endif

#endif  // __complexChar_hh__

