// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.
#ifndef __realDouble_hh__
#define __realDouble_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_realDouble
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_realDouble
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_realDouble
#endif



#ifndef __PortTypes_hh_EXTERNAL_GUARD__
#define __PortTypes_hh_EXTERNAL_GUARD__
#include "ossie/PortTypes.h"
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif



_CORBA_MODULE standardInterfaces

_CORBA_MODULE_BEG

#ifndef __standardInterfaces_mrealDouble__
#define __standardInterfaces_mrealDouble__
  class realDouble;
  class _objref_realDouble;
  class _impl_realDouble;
  
  typedef _objref_realDouble* realDouble_ptr;
  typedef realDouble_ptr realDoubleRef;

  class realDouble_Helper {
  public:
    typedef realDouble_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_realDouble, realDouble_Helper> realDouble_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_realDouble,realDouble_Helper > realDouble_out;

#endif

  // interface realDouble
  class realDouble {
  public:
    // Declarations for this interface type.
    typedef realDouble_ptr _ptr_type;
    typedef realDouble_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static inline _ptr_type _fromObjRef(omniObjRef* o) {
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_realDouble :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    // IDL operations
    void pushPacket(const ::PortTypes::DoubleSequence& I);

    // Constructors
    inline _objref_realDouble()  { _PR_setobj(0); }  // nil
    _objref_realDouble(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_realDouble();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_realDouble(const _objref_realDouble&);
    _objref_realDouble& operator = (const _objref_realDouble&);
    // not implemented

    friend class realDouble;
  };

  class _pof_realDouble : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_realDouble() : _OMNI_NS(proxyObjectFactory)(realDouble::_PD_repoId) {}
    virtual ~_pof_realDouble();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_realDouble :
    public virtual omniServant
  {
  public:
    virtual ~_impl_realDouble();

    virtual void pushPacket(const ::PortTypes::DoubleSequence& I) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_realDouble;

_CORBA_MODULE_END



_CORBA_MODULE POA_standardInterfaces
_CORBA_MODULE_BEG

  class realDouble :
    public virtual standardInterfaces::_impl_realDouble,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~realDouble();

    inline ::standardInterfaces::realDouble_ptr _this() {
      return (::standardInterfaces::realDouble_ptr) _do_this(::standardInterfaces::realDouble::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_standardInterfaces
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, standardInterfaces::realDouble_ptr _s);
void operator<<=(::CORBA::Any& _a, standardInterfaces::realDouble_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, standardInterfaces::realDouble_ptr& _s);



inline void
standardInterfaces::realDouble::_marshalObjRef(::standardInterfaces::realDouble_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}



#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_realDouble
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_realDouble
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_realDouble
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_realDouble
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_realDouble
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_realDouble
#endif

#endif  // __realDouble_hh__

