// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __stereoSound_hh__
#define __stereoSound_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_stereoSound
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_stereoSound
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_stereoSound
#endif



#ifndef __PortTypes_hh_EXTERNAL_GUARD__
#define __PortTypes_hh_EXTERNAL_GUARD__
#include "ossie/PortTypes.h"
#endif



#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE standardInterfaces

_CORBA_MODULE_BEG

#ifndef __standardInterfaces_mstereoSound__
#define __standardInterfaces_mstereoSound__

  class stereoSound;
  class _objref_stereoSound;
  class _impl_stereoSound;
  
  typedef _objref_stereoSound* stereoSound_ptr;
  typedef stereoSound_ptr stereoSoundRef;

  class stereoSound_Helper {
  public:
    typedef stereoSound_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_stereoSound, stereoSound_Helper> stereoSound_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_stereoSound,stereoSound_Helper > stereoSound_out;

#endif

  // interface stereoSound
  class stereoSound {
  public:
    // Declarations for this interface type.
    typedef stereoSound_ptr _ptr_type;
    typedef stereoSound_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_stereoSound :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    void pushPacket(const PortTypes::ShortSequence& left, const PortTypes::ShortSequence& right);

    inline _objref_stereoSound()  { _PR_setobj(0); }  // nil
    _objref_stereoSound(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_stereoSound();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_stereoSound(const _objref_stereoSound&);
    _objref_stereoSound& operator = (const _objref_stereoSound&);
    // not implemented

    friend class stereoSound;
  };

  class _pof_stereoSound : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_stereoSound() : _OMNI_NS(proxyObjectFactory)(stereoSound::_PD_repoId) {}
    virtual ~_pof_stereoSound();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_stereoSound :
    public virtual omniServant
  {
  public:
    virtual ~_impl_stereoSound();

    virtual void pushPacket(const PortTypes::ShortSequence& left, const PortTypes::ShortSequence& right) = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


  _CORBA_MODULE_VAR _dyn_attr const ::CORBA::TypeCode_ptr _tc_stereoSound;

_CORBA_MODULE_END



_CORBA_MODULE POA_standardInterfaces
_CORBA_MODULE_BEG

  class stereoSound :
    public virtual standardInterfaces::_impl_stereoSound,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~stereoSound();

    inline ::standardInterfaces::stereoSound_ptr _this() {
      return (::standardInterfaces::stereoSound_ptr) _do_this(::standardInterfaces::stereoSound::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_standardInterfaces
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr

void operator<<=(::CORBA::Any& _a, standardInterfaces::stereoSound_ptr _s);
void operator<<=(::CORBA::Any& _a, standardInterfaces::stereoSound_ptr* _s);
_CORBA_Boolean operator>>=(const ::CORBA::Any& _a, standardInterfaces::stereoSound_ptr& _s);



inline void
standardInterfaces::stereoSound::_marshalObjRef(::standardInterfaces::stereoSound_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_stereoSound
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_stereoSound
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_stereoSound
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_stereoSound
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_stereoSound
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_stereoSound
#endif

#endif  // __stereoSound_hh__

